// Code generated by internal/gen. DO NOT EDIT.

// Package consumer05 reaches through an EMITTING domain (emit.Maneuver) to a
// telemetry-specific field of its outward representation. The outward-format
// migration removes that field, so this dependent is forced to change. One of N
// identical dependents; the coupled arm's forced-edit count is N. Fails to build
// under -tags repv2 because its own source names Record().BurnSeconds.
package consumer05

import "github.com/verocorp/go-ddd/rationale/changeability/nooutward/emit"

// Use reaches through the emitted outward representation to a wire-format field.
func Use(m emit.Maneuver) int64 {
	return m.Record().BurnSeconds
}
