// Code generated by internal/gen. DO NOT EDIT.

// Package consumer03 holds the PURE domain object (nav.Maneuver) and reads it
// through a domain accessor — never the outward representation. The outward-format
// migration forces 0 edits on it. One of N identical dependents; the decoupled
// arm's forced-edit count stays 0 for any N.
package consumer03

import "github.com/verocorp/go-ddd/rationale/changeability/nooutward/nav"

// Use reads the domain object and nothing outward.
func Use(m nav.Maneuver) int64 {
	return m.BurnMillis()
}
